import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "en" | "am";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.search": "Search",
    "nav.about": "About",
    "nav.contact": "Contact",
    "nav.support": "Support",
    "nav.faq": "FAQ",
    "nav.signin": "Sign In",
    "nav.signup": "Sign Up",
    "nav.profile": "My Profile",
    "nav.favorites": "Favorites",
    "nav.messages": "Messages",
    "nav.dashboard": "Dashboard",
    "nav.admin": "Admin Panel",
    "nav.logout": "Log Out",
    "nav.createListing": "Create Listing",
    
    // Hero
    "hero.title": "Get Your Home",
    "hero.titleHighlight": "with Free",
    "hero.subtitle": "Get Your Home with Free",
    "hero.description": "Find homes in Ethiopia with no fees, no agents, and no payments. Delux connects people directly — simple, fast, and free.",
    "hero.shortDesc": "Delux is a community-driven housing platform in Ethiopia. We help people find and list homes without charging any money.",
    "hero.searchPlaceholder": "Search by location, property type...",
    "hero.search": "Search",
    "hero.propertyType": "Property Type",
    "hero.rentSell": "Rent / Sell",
    "hero.location": "Location",
    "hero.forRent": "For Rent",
    "hero.forSell": "For Sell",
    "hero.browseFree": "Browse Free Homes",
    "hero.listHome": "List Your Home",
    "hero.freeService": "Free Service",
    "hero.listedHomes": "Listed Homes",
    "hero.happyFamilies": "Happy Families",
    "hero.findingPopular": "Finding the Most Popular Homes",
    
    // Property
    "property.bedrooms": "Bedrooms",
    "property.bathrooms": "Bathrooms",
    "property.area": "Area",
    "property.forRent": "For Rent",
    "property.forSale": "For Sale",
    "property.furnished": "Furnished",
    "property.unfurnished": "Unfurnished",
    "property.available": "Available",
    "property.unavailable": "Unavailable",
    "property.contactOwner": "Contact Owner",
    "property.compare": "Compare",
    "property.addToCompare": "Add to Compare",
    "property.removeFromCompare": "Remove from Compare",
    "property.viewDetails": "View Details",
    "property.contact": "Contact",
    "property.description": "Description",
    "property.features": "Features",
    "property.postedBy": "Posted by",
    "property.viewPhone": "View Phone Number",
    "property.save": "Save",
    "property.saved": "Saved",
    "property.price": "Price",
    "property.pricePerMonth": "/month",
    "property.free": "Free",
    "property.negotiable": "Negotiable",
    
    // Search Page
    "search.title": "Find Your",
    "search.titleHighlight": "Perfect Home",
    "search.propertiesAvailable": "properties available",
    "search.filters": "Filters",
    "search.propertyType": "Property Type",
    "search.allTypes": "All Types",
    "search.listingType": "Listing Type",
    "search.all": "All",
    "search.location": "Location",
    "search.allLocations": "All Locations",
    "search.bedrooms": "Bedrooms",
    "search.any": "Any",
    "search.priceRange": "Price Range (ETB)",
    "search.furnishedOnly": "Furnished Only",
    "search.amenities": "Amenities",
    "search.search": "Search",
    "search.clearFilters": "Clear all filters",
    "search.noProperties": "No properties found",
    "search.noPropertiesDesc": "Try adjusting your filters to see more results",
    "search.grid": "Grid",
    "search.map": "Map",
    "search.narrowDown": "Narrow down your property search",
    "search.results": "Search Results",
    "search.propertiesFound": "properties found",
    "search.clearFiltersLink": "Clear filters",
    "search.noMatch": "No properties found matching your criteria.",
    
    // Listing Form
    "listing.title": "List Your Home with Delux",
    "listing.subtitle": "Free. Simple. Trusted in Ethiopia.",
    "listing.whatToDo": "What would you like to do?",
    "listing.forRent": "For Rent",
    "listing.rentDesc": "Rent your home",
    "listing.forSell": "For Sell",
    "listing.sellDesc": "Sell your property",
    "listing.propertyType": "Property Type",
    "listing.chooseLocation": "Choose Property Location",
    "listing.city": "City",
    "listing.selectCity": "Select city",
    "listing.area": "Area",
    "listing.selectArea": "Select area",
    "listing.details": "Property Details",
    "listing.titleOptional": "Title (optional)",
    "listing.titlePlaceholder": "e.g., Modern Family Home",
    "listing.bedrooms": "Bedrooms",
    "listing.bathrooms": "Bathrooms",
    "listing.furnishing": "Furnishing",
    "listing.furnished": "Furnished",
    "listing.unfurnished": "Unfurnished",
    "listing.description": "Description",
    "listing.descPlaceholder": "Describe your property...",
    "listing.addPhotos": "Add Photos",
    "listing.dragDrop": "Drag & drop images or click to browse",
    "listing.maxImages": "Maximum 5 images, 5MB each",
    "listing.price": "Price (ETB)",
    "listing.pricePlaceholder": "e.g., 15000",
    "listing.priceOptional": "Price (optional)",
    "listing.next": "Next",
    "listing.back": "Back",
    "listing.submit": "Submit Listing",
    "listing.submitting": "Creating Listing...",
    "listing.success": "Listing Created!",
    "listing.successDesc": "Your property has been listed successfully.",
    "listing.signInRequired": "Sign In Required",
    "listing.signInDesc": "Please sign in to list your property.",
    "listing.verificationRequired": "Verification Required",
    "listing.verificationDesc": "To protect our community, you need to verify your account before posting property listings.",
    "listing.verifyAccount": "Verify Account",
    
    // Property Details
    "details.back": "Back",
    "details.notFound": "Property Not Found",
    "details.notFoundDesc": "The property you're looking for doesn't exist.",
    "details.backToHome": "Back to Home",
    "details.phoneNumber": "Phone Number",
    "details.signInToContact": "Sign in to contact the owner",
    
    // Auth
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Full Name",
    "auth.phone": "Phone Number",
    "auth.forgotPassword": "Forgot Password?",
    "auth.noAccount": "Don't have an account?",
    "auth.hasAccount": "Already have an account?",
    "auth.orContinueWith": "Or continue with",
    
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.overview": "Overview",
    "dashboard.totalViews": "Total Views",
    "dashboard.totalInquiries": "Total Inquiries",
    "dashboard.activeListings": "Active Listings",
    "dashboard.responseRate": "Response Rate",
    "dashboard.recentActivity": "Recent Activity",
    "dashboard.propertyPerformance": "Property Performance",
    "dashboard.inquiriesTrend": "Inquiries Trend",
    "dashboard.listingDistribution": "Listing Distribution",
    "dashboard.noActivity": "No recent activity. Your inquiries will appear here.",
    "dashboard.noProperties": "No properties yet. Create your first listing!",
    "dashboard.noListings": "No listings yet",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Something went wrong",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.view": "View",
    "common.submit": "Submit",
    "common.back": "Back",
    "common.next": "Next",
    "common.all": "All",
    "common.verified": "Verified",
    "common.goHome": "Go Home",
    
    // Footer
    "footer.tagline": "Delux — a free housing connection platform. It's connection. Delux connects people, not payments.",
    "footer.company": "Company",
    "footer.support": "Support",
    "footer.listings": "Listings",
    "footer.aboutUs": "About Us",
    "footer.howItWorks": "How It Works",
    "footer.careers": "Careers",
    "footer.press": "Press",
    "footer.helpCenter": "Help Center",
    "footer.safety": "Safety",
    "footer.terms": "Terms of Service",
    "footer.privacy": "Privacy Policy",
    "footer.browseHomes": "Browse Homes",
    "footer.listProperty": "List Property",
    "footer.popularAreas": "Popular Areas",
    "footer.rights": "All rights reserved.",
    "footer.madeWith": "Made with ❤️ in Ethiopia",
    "footer.contact": "Contact",
    "footer.supportUs": "Support Us",
    "footer.favorites": "Favorites",
    
    // Reviews
    "reviews.title": "Reviews",
    "reviews.writeReview": "Write a Review",
    "reviews.rating": "Rating",
    "reviews.comment": "Your Review",
    "reviews.submit": "Submit Review",
    "reviews.noReviews": "No reviews yet",
    
    // Notifications
    "notifications.title": "Notifications",
    "notifications.markAllRead": "Mark all as read",
    "notifications.noNotifications": "No notifications",
    
    // Contact
    "contact.telegram": "Telegram",
    "contact.tiktok": "TikTok",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.title": "Get in Touch",
    "contact.subtitle": "Have questions or need assistance? We're here to help! Reach out to us through any of the channels below.",
    "contact.callUs": "Call us directly for immediate assistance",
    "contact.emailUs": "Send us an email anytime",
    "contact.telegramContact": "Telegram Contact",
    "contact.telegramMsg": "Message us on Telegram",
    "contact.telegramChannel": "Telegram Channel",
    "contact.telegramChannelMsg": "Join our Telegram channel for updates",
    "contact.followUs": "Follow Us on Social Media",
    
    // About Page
    "about.title": "About",
    "about.subtitle": "Get your home with free",
    "about.intro": "Delux is a brand-new, community-driven platform working in Ethiopia. We help people find homes without any payment.",
    "about.noAgents": "No agents. No fees.",
    "about.justConnection": "Just connection.",
    "about.whoWeAre": "Who We Are",
    "about.whoWeAreDesc": "Delux connects homeowners and home seekers in a simple and transparent way. Delux is not a marketplace — it is a community connection.",
    "about.ourMission": "Our Mission",
    "about.ourMissionDesc": "To help people find homes easily and freely by connecting homeowners and seekers across Ethiopia.",
    "about.ourVision": "Our Vision",
    "about.ourVisionDesc": "To become Ethiopia's most trusted free housing connection platform.",
    "about.whyDelux": "Why Delux?",
    "about.100free": "100% Free",
    "about.100freeDesc": "No fees, no payments. Delux connects people, not wallets.",
    "about.communityPowered": "Community Powered",
    "about.communityPoweredDesc": "Built for people, by people. Everyone can participate.",
    "about.ethiopiaFocused": "Ethiopia Focused",
    "about.ethiopiaFocusedDesc": "Designed for local housing needs across Ethiopia.",
    "about.trustedVerified": "Trusted & Verified",
    "about.trustedVerifiedDesc": "All listings verified by our community moderators.",
    "about.whatWeOffer": "What We Offer",
    "about.freeHomeListings": "Free home listings",
    "about.rentSellOptions": "Rent and sell options",
    "about.locationSearch": "Location-based search",
    "about.directConnection": "Direct user connection",
    "about.ourPromise": "Our Promise",
    "about.ourPromiseDesc": "Delux is committed to staying free, simple, and accessible for all Ethiopians.",
    "about.notMarketplace": "Delux is not a marketplace.",
    "about.itsConnection": "It's a connection.",
    "about.exploreHomes": "Explore Homes",
    "about.joinToday": "Join Delux Today",
    
    // About Section (home page)
    "aboutSection.title": "Why Choose Delux?",
    "aboutSection.subtitle": "Your trusted housing connection in Ethiopia",
    "aboutSection.100free": "100% Free",
    "aboutSection.100freeDesc": "No fees or hidden costs. Delux connects people, not wallets.",
    "aboutSection.directConnection": "Direct Connection",
    "aboutSection.directConnectionDesc": "Talk directly to homeowners. No middlemen.",
    "aboutSection.communityFirst": "Community First",
    "aboutSection.communityFirstDesc": "Built for Ethiopian users by the community.",
    "aboutSection.trustedVerified": "Trusted & Verified",
    "aboutSection.trustedVerifiedDesc": "All listings verified by our community moderators.",
    "aboutSection.ownHome": "Own a Home?",
    "aboutSection.ownHomeDesc": "List your home for rent or sale — free and easy. Connect with home seekers across Ethiopia without any fees.",
    "aboutSection.listNow": "Homeowner? List Now",
    "aboutSection.learnMore": "Learn More About Delux",
    
    // Featured Listings
    "featured.title": "Finding the Most",
    "featured.titleHighlight": "Popular Homes",
    "featured.subtitle": "Discover the most sought-after properties in Addis Ababa. All verified and ready for immediate connection.",
    "featured.viewAll": "View All Listings",
    "featured.noProperties": "No properties listed yet.",
    "featured.beFirst": "Be the first to list a property",
    
    // Support Page
    "support.title": "Support",
    "support.subtitle": "Delux is a free platform connecting homeowners and renters in Ethiopia. Your support helps us keep the platform running and growing!",
    "support.buyUs": "Buy us a coffee!",
    "support.contribution": "Every contribution helps us maintain and improve Delux for our community.",
    "support.buyCoffee": "Buy Me a Coffee",
    "support.thanks": "Thank you for being part of the Delux community! 🇪🇹",
    
    // FAQ
    "faq.title": "Frequently Asked",
    "faq.titleHighlight": "Questions",
    "faq.subtitle": "Find answers to common questions about using Delux. Can't find what you're looking for? Contact us!",
    "faq.stillQuestions": "Still have questions?",
    "faq.hereToHelp": "We're here to help! Reach out to us through any of our channels.",
  },
  am: {
    // Navigation
    "nav.home": "መነሻ",
    "nav.search": "ፈልግ",
    "nav.about": "ስለ እኛ",
    "nav.contact": "አግኙን",
    "nav.support": "ድጋፍ",
    "nav.faq": "ተደጋጋሚ ጥያቄዎች",
    "nav.signin": "ግባ",
    "nav.signup": "ተመዝገብ",
    "nav.profile": "መገለጫዬ",
    "nav.favorites": "ምርጫዎች",
    "nav.messages": "መልዕክቶች",
    "nav.dashboard": "ዳሽቦርድ",
    "nav.admin": "አስተዳዳሪ ፓነል",
    "nav.logout": "ውጣ",
    "nav.createListing": "ዝርዝር ፍጠር",
    
    // Hero
    "hero.title": "ቤትዎን ያግኙ",
    "hero.titleHighlight": "በነጻ",
    "hero.subtitle": "ቤትዎን በነጻ ያግኙ",
    "hero.description": "በኢትዮጵያ ውስጥ ያለ ክፍያ፣ ያለ ደላላ እና ያለ ክፍያ ቤቶችን ያግኙ። ዴሉክስ ሰዎችን በቀጥታ ያገናኛል — ቀላል፣ ፈጣን እና ነጻ።",
    "hero.shortDesc": "ዴሉክስ በኢትዮጵያ ውስጥ ያለ ማህበረሰብ-ተኮር የቤት መድረክ ነው። ገንዘብ ሳንከፍል ሰዎች ቤት እንዲያገኙ እና እንዲዘረዝሩ እንረዳለን።",
    "hero.searchPlaceholder": "በአካባቢ፣ በንብረት ዓይነት ፈልግ...",
    "hero.search": "ፈልግ",
    "hero.propertyType": "የንብረት ዓይነት",
    "hero.rentSell": "ኪራይ / ሽያጭ",
    "hero.location": "አካባቢ",
    "hero.forRent": "ለኪራይ",
    "hero.forSell": "ለሽያጭ",
    "hero.browseFree": "ነጻ ቤቶችን ይመልከቱ",
    "hero.listHome": "ቤትዎን ይዘርዝሩ",
    "hero.freeService": "ነጻ አገልግሎት",
    "hero.listedHomes": "የተዘረዘሩ ቤቶች",
    "hero.happyFamilies": "ደስተኛ ቤተሰቦች",
    "hero.findingPopular": "በጣም ታዋቂ ቤቶችን ማግኘት",
    
    // Property
    "property.bedrooms": "መኝታ ክፍሎች",
    "property.bathrooms": "መታጠቢያ ክፍሎች",
    "property.area": "አካባቢ",
    "property.forRent": "ለኪራይ",
    "property.forSale": "ለሽያጭ",
    "property.furnished": "የተደራጀ",
    "property.unfurnished": "ያልተደራጀ",
    "property.available": "ይገኛል",
    "property.unavailable": "አይገኝም",
    "property.contactOwner": "ባለቤቱን አግኙ",
    "property.compare": "አወዳድር",
    "property.addToCompare": "ለንጽጽር ጨምር",
    "property.removeFromCompare": "ከንጽጽር አውጣ",
    "property.viewDetails": "ዝርዝሮችን ተመልከት",
    "property.contact": "አግኙ",
    "property.description": "መግለጫ",
    "property.features": "ባህሪያት",
    "property.postedBy": "የለጠፈው",
    "property.viewPhone": "ስልክ ቁጥር ተመልከት",
    "property.save": "አስቀምጥ",
    "property.saved": "ተቀምጧል",
    "property.price": "ዋጋ",
    "property.pricePerMonth": "/በወር",
    "property.free": "ነጻ",
    "property.negotiable": "የሚደራደር",
    
    // Search Page
    "search.title": "ፍጹም",
    "search.titleHighlight": "ቤትዎን ያግኙ",
    "search.propertiesAvailable": "ንብረቶች ይገኛሉ",
    "search.filters": "ማጣሪያዎች",
    "search.propertyType": "የንብረት ዓይነት",
    "search.allTypes": "ሁሉም ዓይነቶች",
    "search.listingType": "የዝርዝር ዓይነት",
    "search.all": "ሁሉም",
    "search.location": "አካባቢ",
    "search.allLocations": "ሁሉም አካባቢዎች",
    "search.bedrooms": "መኝታ ክፍሎች",
    "search.any": "ማንኛውም",
    "search.priceRange": "የዋጋ ክልል (ብር)",
    "search.furnishedOnly": "የተደራጁ ብቻ",
    "search.amenities": "አገልግሎቶች",
    "search.search": "ፈልግ",
    "search.clearFilters": "ሁሉንም ማጣሪያዎች አጽዳ",
    "search.noProperties": "ምንም ንብረት አልተገኘም",
    "search.noPropertiesDesc": "ተጨማሪ ውጤቶችን ለማየት ማጣሪያዎችዎን ያስተካክሉ",
    "search.grid": "ፍርግርግ",
    "search.map": "ካርታ",
    "search.narrowDown": "የንብረት ፍለጋዎን ያጣሩ",
    "search.results": "የፍለጋ ውጤቶች",
    "search.propertiesFound": "ንብረቶች ተገኝተዋል",
    "search.clearFiltersLink": "ማጣሪያዎችን አጽዳ",
    "search.noMatch": "ከመስፈርትዎ ጋር የሚዛመድ ንብረት አልተገኘም።",
    
    // Listing Form
    "listing.title": "ቤትዎን ከዴሉክስ ጋር ይዘርዝሩ",
    "listing.subtitle": "ነጻ። ቀላል። በኢትዮጵያ የታመነ።",
    "listing.whatToDo": "ምን ማድረግ ይፈልጋሉ?",
    "listing.forRent": "ለኪራይ",
    "listing.rentDesc": "ቤትዎን ያከራዩ",
    "listing.forSell": "ለሽያጭ",
    "listing.sellDesc": "ንብረትዎን ይሽጡ",
    "listing.propertyType": "የንብረት ዓይነት",
    "listing.chooseLocation": "የንብረት አካባቢ ይምረጡ",
    "listing.city": "ከተማ",
    "listing.selectCity": "ከተማ ይምረጡ",
    "listing.area": "አካባቢ",
    "listing.selectArea": "አካባቢ ይምረጡ",
    "listing.details": "የንብረት ዝርዝሮች",
    "listing.titleOptional": "ርዕስ (አማራጭ)",
    "listing.titlePlaceholder": "ለምሳሌ: ዘመናዊ የቤተሰብ ቤት",
    "listing.bedrooms": "መኝታ ክፍሎች",
    "listing.bathrooms": "መታጠቢያ ክፍሎች",
    "listing.furnishing": "ዕቃዎች",
    "listing.furnished": "የተደራጀ",
    "listing.unfurnished": "ያልተደራጀ",
    "listing.description": "መግለጫ",
    "listing.descPlaceholder": "ንብረትዎን ይግለጹ...",
    "listing.addPhotos": "ፎቶዎችን ያክሉ",
    "listing.dragDrop": "ምስሎችን ይጎትቱ እና ይጣሉ ወይም ለማሰስ ይጫኑ",
    "listing.maxImages": "ከፍተኛ 5 ምስሎች፣ እያንዳንዳቸው 5MB",
    "listing.price": "ዋጋ (ብር)",
    "listing.pricePlaceholder": "ለምሳሌ: 15000",
    "listing.priceOptional": "ዋጋ (አማራጭ)",
    "listing.next": "ቀጣይ",
    "listing.back": "ተመለስ",
    "listing.submit": "ዝርዝር አስገባ",
    "listing.submitting": "ዝርዝር በመፍጠር ላይ...",
    "listing.success": "ዝርዝር ተፈጥሯል!",
    "listing.successDesc": "ንብረትዎ በተሳካ ሁኔታ ተዘርዝሯል።",
    "listing.signInRequired": "መግባት ያስፈልጋል",
    "listing.signInDesc": "ንብረትዎን ለመዘርዘር እባክዎ ይግቡ።",
    "listing.verificationRequired": "ማረጋገጫ ያስፈልጋል",
    "listing.verificationDesc": "ማህበረሰባችንን ለመጠበቅ ንብረት ዝርዝሮችን ከመለጠፍዎ በፊት መለያዎን ማረጋገጥ ያስፈልግዎታል።",
    "listing.verifyAccount": "መለያ አረጋግጥ",
    
    // Property Details
    "details.back": "ተመለስ",
    "details.notFound": "ንብረት አልተገኘም",
    "details.notFoundDesc": "የሚፈልጉት ንብረት የለም።",
    "details.backToHome": "ወደ መነሻ ተመለስ",
    "details.phoneNumber": "ስልክ ቁጥር",
    "details.signInToContact": "ባለቤቱን ለማግኘት ይግቡ",
    
    // Auth
    "auth.signIn": "ግባ",
    "auth.signUp": "ተመዝገብ",
    "auth.email": "ኢሜይል",
    "auth.password": "የይለፍ ቃል",
    "auth.name": "ሙሉ ስም",
    "auth.phone": "ስልክ ቁጥር",
    "auth.forgotPassword": "የይለፍ ቃል ረሳኽ?",
    "auth.noAccount": "መለያ የለህም?",
    "auth.hasAccount": "መለያ አለህ?",
    "auth.orContinueWith": "ወይም ቀጥል በ",
    
    // Dashboard
    "dashboard.title": "ዳሽቦርድ",
    "dashboard.overview": "አጠቃላይ እይታ",
    "dashboard.totalViews": "ጠቅላላ እይታዎች",
    "dashboard.totalInquiries": "ጠቅላላ ጥያቄዎች",
    "dashboard.activeListings": "ንቁ ዝርዝሮች",
    "dashboard.responseRate": "የምላሽ መጠን",
    "dashboard.recentActivity": "የቅርብ ጊዜ እንቅስቃሴ",
    "dashboard.propertyPerformance": "የንብረት አፈጻጸም",
    "dashboard.inquiriesTrend": "የጥያቄዎች አዝማሚያ",
    "dashboard.listingDistribution": "የዝርዝር ስርጭት",
    "dashboard.noActivity": "የቅርብ ጊዜ እንቅስቃሴ የለም። ጥያቄዎችዎ እዚህ ይታያሉ።",
    "dashboard.noProperties": "ገና ንብረቶች የሉም። የመጀመሪያውን ዝርዝርዎን ይፍጠሩ!",
    "dashboard.noListings": "ገና ዝርዝሮች የሉም",
    
    // Common
    "common.loading": "በመጫን ላይ...",
    "common.error": "የሆነ ነገር ተሳስቷል",
    "common.save": "አስቀምጥ",
    "common.cancel": "ሰርዝ",
    "common.delete": "ሰርዝ",
    "common.edit": "አርትዕ",
    "common.view": "ተመልከት",
    "common.submit": "አስገባ",
    "common.back": "ተመለስ",
    "common.next": "ቀጣይ",
    "common.all": "ሁሉም",
    "common.verified": "የተረጋገጠ",
    "common.goHome": "ወደ መነሻ ሂድ",
    
    // Footer
    "footer.tagline": "ዴሉክስ — ነጻ የቤት ማገናኛ መድረክ። ግንኙነት ነው። ዴሉክስ ሰዎችን ያገናኛል፣ ክፍያ አይደለም።",
    "footer.company": "ኩባንያ",
    "footer.support": "ድጋፍ",
    "footer.listings": "ዝርዝሮች",
    "footer.aboutUs": "ስለ እኛ",
    "footer.howItWorks": "እንዴት እንደሚሰራ",
    "footer.careers": "ስራዎች",
    "footer.press": "ፕሬስ",
    "footer.helpCenter": "የእገዛ ማዕከል",
    "footer.safety": "ደህንነት",
    "footer.terms": "የአገልግሎት ውል",
    "footer.privacy": "የግላዊነት ፖሊሲ",
    "footer.browseHomes": "ቤቶችን ይመልከቱ",
    "footer.listProperty": "ንብረት ይመዝገቡ",
    "footer.popularAreas": "ታዋቂ አካባቢዎች",
    "footer.rights": "መብቱ በህግ የተጠበቀ ነው።",
    "footer.madeWith": "በኢትዮጵያ ❤️ ተሰርቷል",
    "footer.contact": "አግኙን",
    "footer.supportUs": "ድጉሱን",
    "footer.favorites": "ምርጫዎች",
    
    // Reviews
    "reviews.title": "ግምገማዎች",
    "reviews.writeReview": "ግምገማ ጻፍ",
    "reviews.rating": "ደረጃ",
    "reviews.comment": "ግምገማዎ",
    "reviews.submit": "ግምገማ አስገባ",
    "reviews.noReviews": "ገና ግምገማ የለም",
    
    // Notifications
    "notifications.title": "ማሳወቂያዎች",
    "notifications.markAllRead": "ሁሉንም እንደተነበበ ምልክት አድርግ",
    "notifications.noNotifications": "ማሳወቂያ የለም",
    
    // Contact
    "contact.telegram": "ቴሌግራም",
    "contact.tiktok": "ቲክቶክ",
    "contact.phone": "ስልክ",
    "contact.email": "ኢሜይል",
    "contact.title": "ያግኙን",
    "contact.subtitle": "ጥያቄዎች አሉዎት ወይም እገዛ ይፈልጋሉ? ለመርዳት ዝግጁ ነን! ከታች ባሉ ማንኛውም ቻናሎች ያግኙን።",
    "contact.callUs": "ለፈጣን እገዛ በቀጥታ ይደውሉልን",
    "contact.emailUs": "በማንኛውም ጊዜ ኢሜይል ይላኩልን",
    "contact.telegramContact": "የቴሌግራም አድራሻ",
    "contact.telegramMsg": "በቴሌግራም ያግኙን",
    "contact.telegramChannel": "የቴሌግራም ቻናል",
    "contact.telegramChannelMsg": "ለዝማኔዎች የቴሌግራም ቻናላችንን ይቀላቀሉ",
    "contact.followUs": "በማህበራዊ ሚዲያ ይከተሉን",
    
    // About Page
    "about.title": "ስለ",
    "about.subtitle": "ቤትዎን በነጻ ያግኙ",
    "about.intro": "ዴሉክስ በኢትዮጵያ ውስጥ የሚሰራ አዲስ፣ ማህበረሰብ-ተኮር መድረክ ነው። ያለ ምንም ክፍያ ሰዎች ቤት እንዲያገኙ እንረዳለን።",
    "about.noAgents": "ደላላ የለም። ክፍያ የለም።",
    "about.justConnection": "ግንኙነት ብቻ።",
    "about.whoWeAre": "እኛ ማን ነን",
    "about.whoWeAreDesc": "ዴሉክስ የቤት ባለቤቶችን እና የቤት ፈላጊዎችን በቀላል እና ግልጽ መንገድ ያገናኛል። ዴሉክስ ገበያ አይደለም — ማህበረሰብ ግንኙነት ነው።",
    "about.ourMission": "ተልዕኮአችን",
    "about.ourMissionDesc": "በኢትዮጵያ ውስጥ ያሉ የቤት ባለቤቶችን እና ፈላጊዎችን በማገናኘት ሰዎች ቤቶችን በቀላሉ እና በነጻ እንዲያገኙ መርዳት።",
    "about.ourVision": "ራዕያችን",
    "about.ourVisionDesc": "የኢትዮጵያ በጣም የታመነ ነጻ የቤት ማገናኛ መድረክ መሆን።",
    "about.whyDelux": "ለምን ዴሉክስ?",
    "about.100free": "100% ነጻ",
    "about.100freeDesc": "ክፍያ የለም፣ ገንዘብ የለም። ዴሉክስ ሰዎችን ያገናኛል፣ ኪስ ቦርሳዎችን አይደለም።",
    "about.communityPowered": "በማህበረሰብ የሚንቀሳቀስ",
    "about.communityPoweredDesc": "ለሰዎች፣ በሰዎች የተገነባ። ሁሉም ሊሳተፍ ይችላል።",
    "about.ethiopiaFocused": "ኢትዮጵያን ያማከለ",
    "about.ethiopiaFocusedDesc": "በኢትዮጵያ ውስጥ ላሉ የቤት ፍላጎቶች የተነደፈ።",
    "about.trustedVerified": "የታመነ እና የተረጋገጠ",
    "about.trustedVerifiedDesc": "ሁሉም ዝርዝሮች በማህበረሰብ አስተዳዳሪዎቻችን ተረጋግጠዋል።",
    "about.whatWeOffer": "የምናቀርበው",
    "about.freeHomeListings": "ነጻ የቤት ዝርዝሮች",
    "about.rentSellOptions": "የኪራይ እና የሽያጭ አማራጮች",
    "about.locationSearch": "በአካባቢ ላይ የተመሰረተ ፍለጋ",
    "about.directConnection": "ቀጥተኛ የተጠቃሚ ግንኙነት",
    "about.ourPromise": "ቃል ኪዳናችን",
    "about.ourPromiseDesc": "ዴሉክስ ለሁሉም ኢትዮጵያውያን ነጻ፣ ቀላል እና ተደራሽ ሆኖ ለመቆየት ቁርጠኛ ነው።",
    "about.notMarketplace": "ዴሉክስ ገበያ አይደለም።",
    "about.itsConnection": "ግንኙነት ነው።",
    "about.exploreHomes": "ቤቶችን ያስሱ",
    "about.joinToday": "ዛሬ ዴሉክስን ይቀላቀሉ",
    
    // About Section (home page)
    "aboutSection.title": "ለምን ዴሉክስን ይምረጡ?",
    "aboutSection.subtitle": "በኢትዮጵያ ውስጥ የታመነ የቤት ማገናኛ",
    "aboutSection.100free": "100% ነጻ",
    "aboutSection.100freeDesc": "ክፍያ ወይም የተደበቀ ወጪ የለም። ዴሉክስ ሰዎችን ያገናኛል፣ ኪስ ቦርሳዎችን አይደለም።",
    "aboutSection.directConnection": "ቀጥተኛ ግንኙነት",
    "aboutSection.directConnectionDesc": "ከቤት ባለቤቶች ጋር በቀጥታ ይነጋገሩ። መካከለኛ ሰው የለም።",
    "aboutSection.communityFirst": "ማህበረሰብ ቅድሚያ",
    "aboutSection.communityFirstDesc": "ለኢትዮጵያ ተጠቃሚዎች በማህበረሰቡ የተገነባ።",
    "aboutSection.trustedVerified": "የታመነ እና የተረጋገጠ",
    "aboutSection.trustedVerifiedDesc": "ሁሉም ዝርዝሮች በማህበረሰብ አስተዳዳሪዎቻችን ተረጋግጠዋል።",
    "aboutSection.ownHome": "ቤት አለዎት?",
    "aboutSection.ownHomeDesc": "ቤትዎን ለኪራይ ወይም ለሽያጭ ይዘርዝሩ — ነጻ እና ቀላል። ያለ ምንም ክፍያ በመላ ኢትዮጵያ ከቤት ፈላጊዎች ጋር ይገናኙ።",
    "aboutSection.listNow": "ቤት ባለቤት ነዎት? አሁን ይዘርዝሩ",
    "aboutSection.learnMore": "ስለ ዴሉክስ ተጨማሪ ይወቁ",
    
    // Featured Listings
    "featured.title": "በጣም ታዋቂ",
    "featured.titleHighlight": "ቤቶችን ማግኘት",
    "featured.subtitle": "በአዲስ አበባ ውስጥ በጣም ተፈላጊ ንብረቶችን ያግኙ። ሁሉም ተረጋግጠው ለፈጣን ግንኙነት ዝግጁ።",
    "featured.viewAll": "ሁሉንም ዝርዝሮች ይመልከቱ",
    "featured.noProperties": "ገና ምንም ንብረት አልተዘረዘረም።",
    "featured.beFirst": "የመጀመሪያው ንብረት ዘርዛሪ ይሁኑ",
    
    // Support Page
    "support.title": "ድጋፍ",
    "support.subtitle": "ዴሉክስ በኢትዮጵያ ውስጥ የቤት ባለቤቶችን እና ተከራዮችን የሚያገናኝ ነጻ መድረክ ነው። ድጋፍዎ መድረኩን ለማስኬድ እና ለማሳደግ ይረዳል!",
    "support.buyUs": "ቡና ይግዙልን!",
    "support.contribution": "ሁሉም ልገሳ ዴሉክስን ለማስቀጠል እና ለማሻሻል ይረዳል።",
    "support.buyCoffee": "ቡና ይግዙልኝ",
    "support.thanks": "የዴሉክስ ማህበረሰብ አካል ስለሆኑ እናመሰግናለን! 🇪🇹",
    
    // FAQ
    "faq.title": "በተደጋጋሚ የሚጠየቁ",
    "faq.titleHighlight": "ጥያቄዎች",
    "faq.subtitle": "ዴሉክስ ስለመጠቀም ለተለመዱ ጥያቄዎች መልሶችን ያግኙ። የሚፈልጉትን ማግኘት አልቻሉም? ያግኙን!",
    "faq.stillQuestions": "አሁንም ጥያቄዎች አሉዎት?",
    "faq.hereToHelp": "ለመርዳት ዝግጁ ነን! በማንኛውም የእኛ ቻናሎች ያግኙን።",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("delux-language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("delux-language", language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
